In [1]:
import numpy as np


In [3]:
list1=[2,4,6,8,10]
arr=np.array(list1)

In [4]:
arr

array([ 2,  4,  6,  8, 10])

In [5]:
arr+1


array([ 3,  5,  7,  9, 11])

In [24]:
list2=[[1,3,5,7,9,11],[0,2,4,6,8,10]]

In [25]:
arr2=np.array(list2,dtype='float')
arr2

array([[ 1.,  3.,  5.,  7.,  9., 11.],
       [ 0.,  2.,  4.,  6.,  8., 10.]])

In [26]:
arr3=arr2.astype('int')
arr3

array([[ 1,  3,  5,  7,  9, 11],
       [ 0,  2,  4,  6,  8, 10]])

In [28]:
arr4=np.array(list2,dtype='bool')
arr4

array([[ True,  True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True,  True]])

In [32]:
arr5=np.array([9,8.7,'y'],dtype='object')
arr5

array([9, 8.7, 'y'], dtype=object)

In [33]:
list3=arr5.tolist()
list3

[9, 8.7, 'y']

In [34]:
type(list3)

list

In [35]:
type(arr5)

numpy.ndarray