In [ ]:
import numpy as np


In [48]:
## this prints the array as a list of integers
l=[1,2,3] # list l is defined
a=np.array(l)  # array() is a fumction in numpy to make arrays
print(a)


[1 2 3]


In [49]:
## this prints the array as a list of strings
l=[1,2,"3"] # list l is defined
a=np.array(l)  # array() is a fumction in numpy to make arrays
print(a)

['1' '2' '3']


In [ ]:
## the nmpy arrays wants the elements to be of same type 

In [50]:
## this prints the array as a list of datatype defined 
l=["1","2",3] # list l is defined
a=np.array(l,int)  # array() is a fumction in numpy to make arrays
print(a)

[1 2 3]


In [51]:
## this gives erroe becoz sring cany be coverted into integer
l=["tush","dish",3] # list l is defined
a=np.array(l,int)  # array() is a fumction in numpy to make arrays
print(a)

ValueError: invalid literal for int() with base 10: 'tush'

In [55]:
a=np.ones(10)
print(a)
a.dtype

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


dtype('float64')

In [56]:
##numpy operations
## the numpy arrays does the bitwise operations
a=np.array([1,2,3,4])
print(a+2)

[3 4 5]


In [47]:
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [23]:
print(a*2)
print(a*b)
print(a**2)
print(a-2)
print(a/2)


[2 4 6]
[ 4 10 18]
[1 4 9]
[-1  0  1]
[0.5 1.  1.5]


In [68]:
# a.sum()

a.mean()

2.0